# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/rob/Desktop/6.s186/6.s186.srcs/sources_1/ip/fused_full_perf/fused_full_perf.xci
# IP: The module: 'fused_full_perf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rob/Desktop/6.s186/6.s186.srcs/sources_1/ip/fused_full_perf/fused_full_perf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fused_full_perf'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/rob/Desktop/6.s186/6.s186.srcs/sources_1/ip/fused_full_perf/fused_full_perf.xci
# IP: The module: 'fused_full_perf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rob/Desktop/6.s186/6.s186.srcs/sources_1/ip/fused_full_perf/fused_full_perf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fused_full_perf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
