#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Jan 13 17:00:03 EST 2020
# SW Build 2615518 on Fri Aug  9 15:53:29 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim fused_tb_behav -key {Behavioral:sim_1:Functional:fused_tb} -tclbatch fused_tb.tcl -log simulate.log"
xsim fused_tb_behav -key {Behavioral:sim_1:Functional:fused_tb} -tclbatch fused_tb.tcl -log simulate.log

